[33mWARNING [0m root:server.py:44 Invalid message from client_4: BadMessage